FROM oven/bun:1.3.7

WORKDIR /usr/src/app

COPY bun.lock package.json turbo.json ./

COPY packages/db/package.json ./packages/db/
COPY packages/eslint-config/package.json ./packages/eslint-config/
COPY packages/queue/package.json ./packages/queue/
COPY packages/utils/package.json ./packages/utils/
COPY packages/typescript-config/package.json ./packages/typescript-config/
COPY apps/web/package.json ./apps/web/package.json

RUN bun install

COPY packages ./packages
COPY apps/web ./apps/web

RUN DATABASE_URL="test" bun db:generate
RUN bun web:build

USER bun

CMD ["bun", "web:start"]
