FROM node:23-alpine

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./apps/web/package.json ./apps/web/package.json

RUN pnpm install

COPY ./apps/web ./apps/web

RUN pnpm db:generate
RUN pnpm build

CMD ["pnpm", "web:start"]