FROM oven/bun:latest

WORKDIR /usr/src/app

COPY bun.lock package.json turbo.json ./

COPY packages/db/package.json ./packages/db/
COPY packages/eslint-config/package.json ./packages/eslint-config/
COPY packages/queue/package.json ./packages/queue/
COPY packages/utils/package.json ./packages/utils/
COPY packages/typescript-config/package.json ./packages/typescript-config/
COPY ./apps/worker/package.json ./apps/worker/package.json

RUN bun install

COPY packages ./packages
COPY ./apps/worker ./apps/worker

RUN DATABASE_URL="test" bun db:generate

USER bun

CMD ["bun", "worker:start"]
